import z from "zod";
import { datetimeSchema } from "./datetime";
import {
  ChildOrderSchema,
  complexOrderStrategyTypeSchema,
  durationSchema,
  OrderActivitySchema,
  OrderLegCollectionSchema,
  orderStrategyTypeSchema,
  priceLinkBasisSchema,
  priceLinkTypeSchema,
  ReplacingOrderSchema,
  sessionSchema,
  specialInstructionSchema,
  statusSchema,
  stopPriceLinkBasisSchema,
  stopPriceLinkTypeSchema,
  stopTypeSchema,
  taxLotMethodSchema,
} from "./order";

/** Same as orderType, but does not have UNKNOWN since this type is not allowed as an input */
export const orderTypeRequestSchema = z.enum([
  "MARKET",
  "LIMIT",
  "STOP",
  "STOP_LIMIT",
  "TRAILING_STOP",
  "CABINET",
  "NON_MARKETABLE",
  "MARKET_ON_CLOSE",
  "EXERCISE",
  "TRAILING_STOP_LIMIT",
  "NET_DEBIT",
  "NET_CREDIT",
  "NET_ZERO",
  "LIMIT_ON_CLOSE",
]);
export type orderTypeRequest = z.infer<typeof orderTypeRequestSchema>;

export const OrderRequestSchema = z.looseObject({
  session: sessionSchema,
  duration: durationSchema,
  orderType: orderTypeRequestSchema,
  cancelTime: datetimeSchema,
  complexOrderStrategyType: complexOrderStrategyTypeSchema,
  quantity: z.number(),
  filledQuantity: z.number(),
  remainingQuantity: z.number(),
  destinationLinkName: z.string(),
  releaseTime: datetimeSchema,
  stopPrice: z.number(),
  stopPriceLinkBasis: stopPriceLinkBasisSchema,
  stopPriceLinkType: stopPriceLinkTypeSchema,
  stopPriceOffset: z.number(),
  stopType: stopTypeSchema,
  priceLinkBasis: priceLinkBasisSchema,
  priceLinkType: priceLinkTypeSchema,
  price: z.number(),
  taxLotMethod: taxLotMethodSchema,
  orderLegCollection: z.array(OrderLegCollectionSchema),
  activationPrice: z.number(),
  specialInstruction: specialInstructionSchema,
  orderStrategyType: orderStrategyTypeSchema,
  orderId: z.int(),
  cancelable: z.boolean().default(false),
  editable: z.boolean().default(false),
  status: statusSchema,
  enteredTime: datetimeSchema,
  closeTime: datetimeSchema,
  accountNumber: z.int(),
  orderActivityCollection: z.array(OrderActivitySchema),
  replacingOrderCollection: z.array(ReplacingOrderSchema),
  childOrderStrategies: z.array(ChildOrderSchema),
  statusDescription: z.string(),
});
export type OrderRequest = z.infer<typeof OrderRequestSchema>;
